pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  environment {
    // Define environment variables
    PROJECT_ID = 'advance-totem-416000'
    IMAGE = 'gcr.io/$PROJECT_ID/binary-calculator'
    DEPLOYMENT_NAME = 'binary-calculator-deployment'
    KUBECONFIG_CREDENTIALS_ID = 'GitHub_token.' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('Test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Build and Push Image') {
      steps {
        script {
          // Build the Docker image
          sh 'docker build -t $IMAGE:$BUILD_ID .'
          
          // Authenticate with Google Cloud
          sh 'gcloud auth configure-docker'

          // Push the Docker image to Google Container Registry
          sh 'docker push $IMAGE:$BUILD_ID'
        }
      }
    }
    stage ('Deploy to GKE') {
      steps {
        script {
          // Set the Kubernetes context to your GKE cluster
          sh 'gcloud container clusters get-credentials sofe3980u --zone northamerica-northeast1-b --project $PROJECT_ID'
          
          // Use kubectl to set the image in the deployment to the new image
          sh 'kubectl set image deployment/$DEPLOYMENT_NAME binary-calculator=$IMAGE:$BUILD_ID'
        }
      }
    }
  }
  post {
    success {
      sh 'echo "Deployment succeeded!"'
    }
    failure {
      sh 'echo "Deployment failed."'
    }
  }
}
